### PR TITLE
Fix pubsub certificate

### PR DESCRIPTION
**Pull request by pitchum**
Fix for #19

### CODE REVIEW

**Comment by Neustradamus** [comment]
Good job!

**Comment by Neustradamus** [comment]
@pitchum: Why have you closed your PR?

**Comment by pitchum** [comment]
hi @Neustradamus actually, I completely deleted my fork, because development now continue on https://github.com/YunoHost-Apps/prosody_ynh/ (branch testing)

This PR has been implemented here: https://github.com/YunoHost-Apps/prosody_ynh/commit/36bdb12e072c4152c515cdca8fc5a26f8d90049a

**Comment by Neustradamus** [comment]
@pitchum: Nice! :)

**Pull request closed without merging**
